mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: admin
  ports:
    - "3306:3306"
  volumes:
    - ./database:/var/lib/mysql
adminer:
  image: adminer
  environment:
    ADMINER_DESIGN: nette
  ports:
    - 8080:8080
  links:
    - mysql
