nginx:
  image: tutum/nginx
  ports:
    - "80:80"
  links:
    - phpfpm
  volumes:
    - ./nginx/dev.conf:/etc/nginx/sites-enabled/site.conf
    - ./:/usr/share/nginx/html
phpfpm:
  image: phpfpm-mysqli-memcached
  ports:
    - "9000:9000"
  links:
    - mysql
  volumes:
    - ./:/usr/share/nginx/html
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: admin
  ports:
    - "3306:3306"
  volumes:
    - ./database:/var/lib/mysql
adminer:
  image: adminer
  environment:
    ADMINER_DESIGN: nette
  ports:
    - 8080:8080
  links:
    - mysql
